package com.example.hi.List

import com.example.hi.R
import com.example.hi.data.JewelryItem

val searchList = listOf(
    JewelryItem(1, "Bohemian Beaded Layered Bracelet Set", "$9.99", R.drawable.bracelet1),
    JewelryItem(2, "Gold Plated Chain Link Bracelet", "$11.50", R.drawable.bracelet2),
    JewelryItem(3, "Simple Adjustable Rope Bracelet", "$3.99", R.drawable.bracelet3),
    JewelryItem(4, "Vintage Leather Cuff Bracelet", "$14.99", R.drawable.bracelet4),
    JewelryItem(5, "Silver Infinity Charm Bracelet", "$6.25", R.drawable.bracelet5),
    JewelryItem(6, "Minimalist Crystal Bangle Bracelet", "$7.50", R.drawable.bracelet6),
    JewelryItem(7, "6pcs Multi-Color Friendship Bracelets", "$4.99", R.drawable.bracelet7),
    JewelryItem(8, "<Delicate Rose Gold Bracelet Set", "$12.99", R.drawable.bracelet8),
    JewelryItem(9, "Adjustable Sterling Silver Bracelet", "$8.25", R.drawable.bracelet9),
    JewelryItem(10, "Handmade Turquoise Bead Bracelet", "$9.75", R.drawable.bracelet10),
    JewelryItem(11, "5pcs Classic Bracelet", "$5.49", R.drawable.bracelet11),
    JewelryItem(12, "Charm Bracelet with Heart Pendant", "$8.99", R.drawable.bracelet12),
    JewelryItem(13, "Adjustable Crystal Chain Bracelet", "$7.25", R.drawable.bracelet13),
    JewelryItem(14, "Gold Plated Pearl Chain Bracelet", "$10.99", R.drawable.bracelet14),
    JewelryItem(15, "Bohemian Vintage Layered Bracelet", "$9.50", R.drawable.bracelet15),
    JewelryItem(16, "Handmade Infinity Knot Bracelet", "$6.75", R.drawable.bracelet16),
    JewelryItem(17, "Beaded Stone Healing Bracelet", "$12.25", R.drawable.bracelet17),
    JewelryItem(18, "Silver Plated Minimalist Bracelet", "$7.99", R.drawable.bracelet18),
    JewelryItem(19, "2pcs Gold Bracelet", "$8.49", R.drawable.bracelet19),
    JewelryItem(20, "Adjustable Gold Crystal Bangle", "$13.99", R.drawable.bracelet20),
    JewelryItem(1,"2pcs/set Luxury Girls' Ring", "$1,58", R.drawable.ring1),
    JewelryItem(2,"10pcs Vintage  Multilayer", "$9,55",R.drawable.ring2),
    JewelryItem(3,"3pcs/set Sky Blue Heart Shaped Ring", "$2499",R.drawable.ring3),
    JewelryItem(4,"12pcs/set Irregular Geometric Teardrop", "$3580",R.drawable.ring4),
    JewelryItem(5,"CHOSHILAR 25pcs/Set Creative Resin Rings", "$1,58",R.drawable.ring5),
    JewelryItem(6,"2pcs Fashionable Vintage Blue Turquoise", "$9,55",R.drawable.ring6),
    JewelryItem(7,"1pc Women Ring Set, Delicate Jewelry", "$2499",R.drawable.ring7),
    JewelryItem(8,"Women Ring Sets | Womens Women Ring", "$3580",R.drawable.ring8),
    JewelryItem(9,"1pc Simple Crown Design Cubic Zirconia", "$1,58",R.drawable.ring9),
    JewelryItem(10,"15pcs/Set Open Ring Hollow Heart", "$9,55",R.drawable.ring10),
    JewelryItem(11,"2pcs Black & White Couples Hip Hop", "$2499",R.drawable.ring11),
    JewelryItem(12,"Women Ring Sets | Fashion Women Ring", "$3580",R.drawable.ring12),
    JewelryItem(13,"2pcs Blue And Green Crystal Inlaid Ring Set ", "$3580",R.drawable.ring13),
    JewelryItem(14,"6pcs/Set Trendy Chunky Geometric", "$1,58",R.drawable.ring14),
    JewelryItem(15,"2pcs Alloy Bohemian Style Turquoise Ring", "$9,55",R.drawable.ring15),
    JewelryItem(16,"1pair Women's Water Drop Shaped Inlaid", "$2499",R.drawable.ring16),
    JewelryItem(17,"6pcs Simple Heart Shaped Acrylic", "$3580",R.drawable.ring17),
    JewelryItem(18,"6pcs Random Vintage Green Oil Drop Heart", "$1,58",R.drawable.ring18),
    JewelryItem(19,"1pair Sparkling Diamond Ring Set", "$9,55",R.drawable.ring19),
    JewelryItem(20,"6pcs Random Vintage Green Oil Drop Heart", "$2499",R.drawable.ring20),
    JewelryItem(1, "Classic Leather Strap Quartz Watch", "$25.99", R.drawable.watch1),
    JewelryItem(2, "Stainless Steel Gold Plated Watch", "$35.50", R.drawable.watch2),
    JewelryItem(3, "Minimalist Rose Gold Mesh Watch", "$22.99", R.drawable.watch3),
    JewelryItem(4, "Vintage Pocket Chain Watch", "$18.75", R.drawable.watch4),
    JewelryItem(5, "Luxury Diamond Inlaid Wristwatch", "$45.99", R.drawable.watch5),
    JewelryItem(6, "Waterproof Analog Sports Watch", "$29.99", R.drawable.watch6),
    JewelryItem(7, "Casual Unisex Digital Watch", "$15.99", R.drawable.watch7),
    JewelryItem(8, "Modern Black Stainless Watch & Infinity Charm Bracelet", "$31.50", R.drawable.watch8),
    JewelryItem(9, "Gold Chain Designer Analog Watch", "$40.25", R.drawable.watch9),
    JewelryItem(10, "Simple Leather Band Women's Watch", "$19.75", R.drawable.watch10),
    JewelryItem(11, "Square Face Stainless Steel Watch &  Heart Bracelet (2pcs/Set) ", "$28.99", R.drawable.watch11),
    JewelryItem(12, "Classic Roman Numeral Dial Watch", "$35.99", R.drawable.watch12),
    JewelryItem(13, "Luxury Sapphire Crystal Watch", "$50.99", R.drawable.watch13),
    JewelryItem(14, "Ultra-Thin Mesh Band Quartz Watch", "$27.75", R.drawable.watch14),
    JewelryItem(15, "Modern Chronograph Sports Watch", "$32.99", R.drawable.watch15),
    JewelryItem(16, "Digital Smart Fitness Tracker Watch", "$24.99", R.drawable.watch16),
    JewelryItem(17, "Elegant Gold Stainless Steel Strap", "$75.50", R.drawable.watch17),
    JewelryItem(18, "Silver Dial Chronograph Watch", "$49.99", R.drawable.watch18),
    JewelryItem(19, "Casual Brown Leather Analog Watch", "$21.99", R.drawable.watch19),
    JewelryItem(20, "Elegant Pearl Dial Women's Watch", "$38.75", R.drawable.watch20),
    JewelryItem(1,"2in1 van cleef necklace", "$1,58", R.drawable.necklace1),
    JewelryItem(2,"Women's Necklace Silver Heart", "$9,55", R.drawable.necklace2),
    JewelryItem(3,"3pcs/set Beautiful Star Moon Necklace", "$2499", R.drawable.necklace3),
    JewelryItem(4,"Butterfly Double Layer Necklace", "$8", R.drawable.necklace4),
    JewelryItem(5,"CHOSHILAR 25pcs/Set Creative Resin Rings", "$1,58", R.drawable.necklace5),
    JewelryItem(6,"2pcs Fashionable Vintage Blue Turquoise", "$9,55", R.drawable.necklace6),
    JewelryItem(7,"1pc Women Ring Set, Delicate Jewelry", "$2499", R.drawable.necklace7),
    JewelryItem(8,"1 pièce Collier simple & Personnalisé Design", "$3580", R.drawable.necklace8),
    JewelryItem(9,"1pc Simple Crown Design Cubic Zirconia", "$1,58", R.drawable.necklace9),
    JewelryItem(10,"15pcs/Set Open Ring Hollow Heart", "$9,55", R.drawable.necklace10),
    JewelryItem(11,"2pcs Black & White Couples Hip Hop", "$2499", R.drawable.necklace11),
    JewelryItem(12,"Women Ring Sets | Fashion Women Ring", "$3580", R.drawable.necklace12),
    JewelryItem(13,"2pcs Blue And Green Crystal Inlaid Ring Set ", "$3580", R.drawable.necklace13),
    JewelryItem(14,"6pcs/Set Trendy Chunky Geometric", "$1,58",R.drawable.necklace14),
    JewelryItem(15,"2pcs Alloy Bohemian Style Turquoise Ring", "$9,55", R.drawable.necklace15),
    JewelryItem(16,"1pair Women's Water Drop Shaped Inlaid", "$2499", R.drawable.necklace16),
    JewelryItem(17,"6pcs Simple Heart Shaped Acrylic", "$3580", R.drawable.necklace17),
    JewelryItem(18,"6pcs Random Vintage Green Oil Drop Heart", "$1,58", R.drawable.necklace18),
    JewelryItem(19,"1pair Sparkling Diamond Ring Set", "$9,55",R.drawable.necklace19),
    JewelryItem(20,"Collier Pendentif Simple Rayon", "$2499", R.drawable.necklace20),
    JewelryItem(1, "Elegant Crystal Drop Earrings", "$5.99", R.drawable.earring1),
    JewelryItem(2, "Vintage Bohemian Hoop Earrings", "$8.49", R.drawable.earring2),
    JewelryItem(3, "Gold Plated Pearl Stud Earrings", "$3.75", R.drawable.earring3),
    JewelryItem(4, "Sparkling Diamond Stud Earrings", "$12.99", R.drawable.earring4),
    JewelryItem(5, "Silver Heart Shaped Drop Earrings", "$6.25", R.drawable.earring5),
    JewelryItem(6, "Minimalist Geometric Hoop Earrings", "$7.99", R.drawable.earring6),
    JewelryItem(7, "6 Pairs of Multi-Color Stud Earrings", "$4.49", R.drawable.earring7),
    JewelryItem(8, "Statement Crystal Chandelier Earrings", "$15.99", R.drawable.earring8),
    JewelryItem(9, "Vintage Bronze Leaf Earrings", "$5.50", R.drawable.earring9),
    JewelryItem(10, "Classic Round CZ Stud Earrings", "$6.75", R.drawable.earring10),
    JewelryItem(11, "1 Pair Minimalist Silver Drop Earrings", "$9.25", R.drawable.earring11),
    JewelryItem(12, "Gold Plated Flower Design Earrings", "$8.99", R.drawable.earring12),
    JewelryItem(13, "Butterfly Shaped Crystal Earrings", "$7.25", R.drawable.earring13),
    JewelryItem(14, "Cubic Zirconia Halo Stud Earrings", "$6.99", R.drawable.earring14),
    JewelryItem(15, "Handmade Boho Feather Earrings", "$10.50", R.drawable.earring15),
    JewelryItem(16, "Geometric Resin Hoop Earrings", "$5.49", R.drawable.earring16),
    JewelryItem(17, "Star and Moon Pendant Earrings", "$9.99", R.drawable.earring17),
    JewelryItem(18, "Small Round Gold Drop Earrings", "$8.75", R.drawable.earring18),
    JewelryItem(19, "Diamond Inlay Double Ring Earrings", "$11.25", R.drawable.earring19),
    JewelryItem(20, "Pearl and Crystal Cluster Earrings", "$14.99", R.drawable.earring20)
)